USE customer_behavior;
SELECT * FROM customer LIMIT 10;

-- Business Questions:
-- 1. What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) as Revenue
FROM customer
GROUP BY gender;

-- 2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
where discount_applied = 'Yes' AND purchase_amount >= (
	SELECT AVG(purchase_amount)
    FROM customer
);

-- 3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating), 2) AS `Average review rating`
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- 4. Compare the average purchase amounts between Standard and Express shipping. (both correct, 1st mine)
SELECT (
		SELECT AVG(purchase_amount)
		FROM customer
		WHERE shipping_type = 'Standard') as standard,
		(
		SELECT AVG(purchase_amount)
		FROM customer
		WHERE shipping_type = 'Express') as express
;

SELECT shipping_type, AVG(purchase_amount)
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- 5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, COUNT(customer_id),
ROUND(AVG(purchase_amount), 2) AS average_spend, 
ROUND(SUM(purchase_amount), 2) as total_revenue
FROM customer
GROUP BY subscription_status;

-- 6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- 7. Segment customers into new, returning and loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS(
	SELECT customer_id, previous_purchases,
    CASE
		WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
    FROM customer
)

SELECT customer_segment, COUNT(*) AS `Number of Customers`
FROM customer_type
GROUP BY customer_segment;

-- 8. What are the top 3 most purchased products within each category?
WITH item_count AS (
	SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
    ROW_NUMBER() OVER(partition by category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_count
WHERE item_rank <= 3;

-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- 10. What is the revenue contribution of each group?
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;




